#!/usr/bin/env bash
##
# run_local.sh — Single-machine evaluation entry point for drift-aware fuzzing.
#
# Runs one or more fuzzer-target campaigns using the Magma captain orchestrator.
# Generates a captainrc from command-line options and calls captain/run.sh.
#
# Usage:
#   bash run_local.sh [OPTIONS]
#
# Options:
#   --fuzzers  "F1 F2 ..."   Fuzzers to run (default: "afl aflcd")
#   --targets  "T1 T2 ..."   Magma targets  (default: "sqlite3 libpng")
#   --timeout  DURATION      Per-campaign duration: 10m, 1h, 24h (default: 1h)
#   --reps     N             Repetitions per fuzzer-program pair (default: 1)
#   --outdir   PATH          Output directory (default: ./workdir)
#   --workers  N             Max parallel campaigns (default: all CPU cores)
#   --seed     N             Base FUZZER_SEED; rep i uses seed+i (default: 1000)
#   --help                   Show this message
#
# Example — quick single pair:
#   bash run_local.sh --fuzzers "afl aflcd" --targets "sqlite3" --timeout 1h --reps 2
#
# Example — full AFL pair, all targets, 10 reps:
#   bash run_local.sh \
#     --fuzzers "afl aflcd" \
#     --targets "sqlite3 libpng lua libsndfile libtiff libxml2 poppler php openssl" \
#     --timeout 24h --reps 10 --outdir ./results/afl_pair
#
# Analyzing results after the run:
#   CDFUZZ_BASE=<outdir> CDFUZZ_OUTDIR=<outdir>/plots python3 plot_seed4.py
##
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAGMA="${MAGMA:-$SCRIPT_DIR/magma}"
CAPTAIN="$MAGMA/tools/captain"

# --- Defaults ---
FUZZERS="afl aflcd"
TARGETS="sqlite3 libpng"
TIMEOUT="1h"
REPS=1
OUTDIR="$SCRIPT_DIR/workdir"
WORKERS=""
BASE_SEED=1000

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --fuzzers)  FUZZERS="$2";  shift 2 ;;
        --targets)  TARGETS="$2";  shift 2 ;;
        --timeout)  TIMEOUT="$2";  shift 2 ;;
        --reps)     REPS="$2";     shift 2 ;;
        --outdir)   OUTDIR="$2";   shift 2 ;;
        --workers)  WORKERS="$2";  shift 2 ;;
        --seed)     BASE_SEED="$2"; shift 2 ;;
        --help|-h)
            sed -n '/^# Usage/,/^##$/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "Unknown option: $1" >&2; exit 2 ;;
    esac
done

# --- Validate ---
if ! command -v docker &>/dev/null; then
    echo "ERROR: docker not found. Install Docker and ensure it is in PATH." >&2
    exit 1
fi

if [[ ! -d "$CAPTAIN" ]]; then
    echo "ERROR: captain not found at $CAPTAIN. Is MAGMA set correctly?" >&2
    exit 1
fi

# --- CD parameter table (paper-confirmed best per fuzzer) ------------------
# These values match the paper evaluation (Section IV, Table II).
# Override by exporting AFL_DRIFT_* variables before calling this script.
cd_params_for() {
    local fuzzer="$1"
    case "$fuzzer" in
        aflcd)
            echo "AFL_DRIFT_WINDOW=100 AFL_DRIFT_CONSECUTIVE=3 AFL_DRIFT_COOLDOWN=10 AFL_DRIFT_SOFT_RESET=1 AFL_DRIFT_HAVOC_BOOST=1"
            ;;
        aflfastcd)
            echo "AFL_DRIFT_WINDOW=100 AFL_DRIFT_CONSECUTIVE=3 AFL_DRIFT_COOLDOWN=10 AFL_DRIFT_SOFT_RESET=1 AFL_DRIFT_HAVOC_BOOST=1"
            ;;
        moptaflcd)
            echo "AFL_DRIFT_WINDOW=100 AFL_DRIFT_CONSECUTIVE=5 AFL_DRIFT_COOLDOWN=10 AFL_DRIFT_SOFT_RESET=1 AFL_DRIFT_HAVOC_BOOST=1"
            ;;
        aflpluspluscd)
            echo "AFL_DRIFT_WINDOW=100 AFL_DRIFT_CONSECUTIVE=12 AFL_DRIFT_COOLDOWN=25 AFL_DRIFT_SOFT_RESET=1 AFL_DRIFT_HAVOC_BOOST=1"
            ;;
        fairfuzzcd)
            echo "AFL_DRIFT_WINDOW=100 AFL_DRIFT_CONSECUTIVE=3 AFL_DRIFT_COOLDOWN=10 AFL_DRIFT_SOFT_RESET=1 AFL_DRIFT_HAVOC_BOOST=1"
            ;;
        honggfuzzcd)
            echo "AFL_DRIFT_WINDOW=5 AFL_DRIFT_CONSECUTIVE=2 AFL_DRIFT_COOLDOWN=5 AFL_DRIFT_KEEP_RECENT=50"
            ;;
        *)
            # Baseline fuzzers: no CD parameters needed (variables are ignored)
            echo ""
            ;;
    esac
}

# --- Build per-rep captainrc files and run them ----------------------------
mkdir -p "$OUTDIR"
FUZZERS_ARRAY=($FUZZERS)
TARGETS_ARRAY=($TARGETS)

echo "=========================================="
echo " Drift-Aware Fuzzing — Local Evaluation"
echo "=========================================="
echo "  Fuzzers:  $FUZZERS"
echo "  Targets:  $TARGETS"
echo "  Timeout:  $TIMEOUT per campaign"
echo "  Reps:     $REPS"
echo "  Outdir:   $OUTDIR"
echo "  Base seed: $BASE_SEED"
[[ -n "$WORKERS" ]] && echo "  Workers:  $WORKERS"
echo "=========================================="

for rep in $(seq 0 $((REPS - 1))); do
    FUZZER_SEED=$(( BASE_SEED + rep ))
    REP_OUTDIR="$OUTDIR/rep${rep}"
    CAPTAINRC="$REP_OUTDIR/captainrc"
    mkdir -p "$REP_OUTDIR"

    # Build captainrc for this repetition
    {
        echo "# Auto-generated by run_local.sh (rep=$rep, seed=$FUZZER_SEED)"
        echo "WORKDIR=$REP_OUTDIR"
        echo "REPEAT=1"
        echo "TIMEOUT=$TIMEOUT"
        echo "POLL=5"
        echo "CACHE_ON_DISK=1"
        echo "NO_ARCHIVE=1"
        echo "MAGMA=$MAGMA"
        [[ -n "$WORKERS" ]] && echo "WORKERS=$WORKERS"
        echo ""
        echo "FUZZERS=(${FUZZERS_ARRAY[*]})"
        echo ""
        for fuzzer in "${FUZZERS_ARRAY[@]}"; do
            echo "${fuzzer}_TARGETS=(${TARGETS_ARRAY[*]})"
        done
        echo ""
        echo "# Paired PRNG seed (baseline and CD variant share the same seed per rep)"
        echo "export FUZZER_SEED=$FUZZER_SEED"
        echo ""
        echo "# CD drift parameters (ignored by baseline fuzzers)"
        echo "export AFL_DRIFT_THRESHOLD=0.05"
        echo "export AFL_DRIFT_EMA_ALPHA=0.1"
        echo "export AFL_DRIFT_STAGNATION_FACTOR=0.5"
        echo "export AFL_DRIFT_MAX_RESETS=0"
        echo "export AFL_DRIFT_BOOST_CYCLES=1"
        echo "export AFL_DRIFT_KEEP_RECENT=0"
        echo ""
        echo "# Per-fuzzer CD parameters"
        for fuzzer in "${FUZZERS_ARRAY[@]}"; do
            params="$(cd_params_for "$fuzzer")"
            if [[ -n "$params" ]]; then
                echo "# $fuzzer"
                for kv in $params; do
                    echo "export $kv"
                done
            fi
        done
    } > "$CAPTAINRC"

    echo ""
    echo "--- Rep $rep (seed=$FUZZER_SEED) ---"
    echo "captainrc: $CAPTAINRC"

    cd "$CAPTAIN"
    bash run.sh "$CAPTAINRC"
    cd "$SCRIPT_DIR"

    # Flatten rep results into the shared ar/ tree:
    #   rep<N>/ar/<fuzzer>/<target>/<program>/0/  ->  ar/<fuzzer>/<target>/<program>/<N>/
    shopt -s nullglob
    for cid_dir in "$REP_OUTDIR"/ar/*/*/0; do
        rel="${cid_dir#"$REP_OUTDIR"/ar/}"   # fuzzer/target/program/0
        base="${rel%/0}"                      # fuzzer/target/program
        dest="$OUTDIR/ar/$base/$rep"
        mkdir -p "$dest"
        rsync -a \
            --exclude 'queue/' \
            --exclude 'corpus/' \
            --exclude 'output/' \
            --exclude '.cur_input' \
            --exclude '.synced/' \
            "$cid_dir"/ "$dest"/
    done
    shopt -u nullglob
done

echo ""
echo "=========================================="
echo " All campaigns complete."
echo " Results: $OUTDIR/ar/"
echo ""
echo " Analyze with:"
echo "   CDFUZZ_BASE=$OUTDIR CDFUZZ_OUTDIR=$OUTDIR/plots python3 $SCRIPT_DIR/plot_seed4.py"
echo "=========================================="
